### ISSUE TITLE
Relation Protected Area in OSM no found

### ISSUE THREAD

**Issue by BikeRoad** [osm-search/Nominatim#1867]
Hello.

I have added information to some protected areas in Peru, but for some strange reason they have stopped appearing in the search result of Nominatin. I have noticed it since 06/29/20
On the other hand, in other areas that I have not edited if they appear.
![Sin título](https://user-images.githubusercontent.com/19896035/86372018-42f0d200-bc47-11ea-920a-00f11f8bbada.png)
I list the affected areas.

Reserva Nacional de Paracas
https://www.openstreetmap.org/relation/3907592

Santuario Nacional Lagunas de Mejía
https://www.openstreetmap.org/relation/9551822

Reserva Nacional de Junín
https://www.openstreetmap.org/relation/3905468

Santuario Nacional Los Manglares de Tumbes 
https://www.openstreetmap.org/relation/454406

Refugio de Vida Silvestre Los Pantanos de Villa
https://www.openstreetmap.org/relation/10754617

Laguna del Indio - Dique de los Españoles
https://www.openstreetmap.org/relation/10985813

Lagunas Las Arreviatadas
https://www.openstreetmap.org/relation/10986532

Parque Nacional del Manu
https://www.openstreetmap.org/relation/11256967

Thank you.

**Comment by lonvia** [comment]
Protected areas did not get indexed between June 28th and July 1st due to a software issue caused by the insane relation of [Klamath Forest](https://www.openstreetmap.org/relation/11245090) (has been deleted in the meantime). The issue has been fixed and the servers are back to normal.

**Comment by BikeRoad** [comment]
Hello.

The relations mentioned above are still missing from the search results!!! (04-07-20)

**Comment by lonvia** [comment]
I'm sorry but it's seriously difficult to manually add the protected areas that got missing in that period. Things will sort themselves out with time, latest at the next reimport.
