### ISSUE TITLE
Upgrade issue 3.5.2 -> 3.6.0: search-API returns code 500 "Cannot normalize query string"

### ISSUE THREAD

**Issue by eastclintw00d** [osm-search/Nominatim#2335]
**Describe the bug**
I recently upgraded from 3.5.2 to 3.6.0. Now, the search-API is no longer working. The lookup and reverse examples from the documentation work fine:
```
http://<my_ip>/nominatim/lookup?osm_ids=R146656,W104393803,N240109189
http://<my_ip>/nominatim/reverse?format=xml&lat=52.5487429714954&lon=-1.81602098644987&zoom=18&addressdetails=1
```
but these don't:
```
http://<my_ip>/nominatim/search?q=135+pilkington+avenue,+birmingham&format=xml&polygon_geojson=1&addressdetails=1
http://<my_ip>/nominatim/search?format=xml&addressdetails=1&q=10,Lindenweg,28870,Ottersberg&countrycodes=DE
```
The response looks like this:
```
<error>
  <code>500</code>
  <message>
    Cannot normalize query string (is it a UTF-8 string?)
  </message>
</error>
```

**To Reproduce**
Not sure it can be reproduced. Its probably a local issue.

**Software Environment (please complete the following information):**
- Nominatim version: 3.6.0
- Postgresql version: 10.16
- Postgis version: POSTGIS="2.4.3 r16312" PGSQL="100" GEOS="3.6.2-CAPI-1.10.2 4d2925d6" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.2.3, released 2017/11/20" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.2.1" RASTER
- OS: Ubuntu 18.04

**Hardware Configuration (please complete the following information):**
- RAM: 144GB
- number of CPUs: 24
- type and size of disks: SSD 2TB
- bare metal/AWS/other cloud service: 

**Postgresql Configuration:**

I haven't changed anything during the migration process. 3.5.2 was working fine.

As stated above I believe that this is a local issue with my installation. I have done two migrations in the past but otherwise my knowledge within this environment is limited and any help is appreciated.

**Comment by lonvia** [comment]
Can you run the search with debug output, e.g. `http://<my_ip>/nominatim/search?format=xml&addressdetails=1&q=10,Lindenweg,28870,Ottersberg&countrycodes=DE&debug=1` What does the full error message say?

Also, 3.6.0 has a check script that you can run: `./utils/check_import_finished.php` Does it report any errors?

**Comment by eastclintw00d** [comment]
The debug output is
```
XML-Verarbeitungsfehler: "Junk" nach Dokument-Element
Adresse: http://10.1.30.179/nominatim/search?format=xml&addressdetails=1&q=10,Lindenweg,28870,Ottersberg&countrycodes=DE&debug=1
Zeile Nr. 2, Spalte 1:
<pre><b>Geocode:</b>  'Query' => '10,Lindenweg,28870,Ottersberg'
^
```
and `check_import_finished.php` returns
```
Checking database got created ... OK
Checking nominatim.so module installed ... PHP Fatal error:  Uncaught Nominatim\DatabaseError: [500]: Database query failed

  thrown in /srv/nominatim/Nominatim-3.6.0/lib/DB.php on line 187
```

**Comment by lonvia** [comment]
Please try rerunning `./utils/setup.php --create-functions --enable-diff-updates`. I suspect it doesn't look for the right database module. If it doesn't help, can you try again with `http://<my_ip>/nominatim/search?format=json&addressdetails=1&q=10,Lindenweg,28870,Ottersberg&countrycodes=DE&debug=1`?

**Comment by eastclintw00d** [comment]
`./utils/setup.php --create-functions --enable-diff-updates` did the trick. Everything is working as usual as far as I can see.

Thank you very much for your help!

**Comment by lonvia** [comment]
Yeah, that command actually needs to be run when the location of the database module changes. 

Reopening the ticket as a note to myself to add some words on that into the documentation.

**Comment by eastclintw00d** [comment]
Not sure if this is related but apparently also the updates are broken. I ran `./utils/update.php --import-osmosis-all` and then this happened:

```
Currently at sequence 2976 (17/05/2021 20:21:58) -  indexed
'/srv/nominatim/Nominatim-3.6.0/nominatim/nominatim.py' --database nominatim --port 5432 --threads 1 --verbose -b
WARNING: Starting indexing boundaries using 1 threads
WARNING: Starting boundaries rank 5 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 5

WARNING: Starting boundaries rank 6 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 6

WARNING: Starting boundaries rank 7 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 7

WARNING: Starting boundaries rank 8 (using batch size 1)
Traceback (most recent call last):
  File "/srv/nominatim/Nominatim-3.6.0/nominatim/indexer/db.py", line 99, in is_done
    if self.conn.poll() == psycopg2.extensions.POLL_OK:
psycopg2.ProgrammingError: function get_places_for_addr_tags(smallint, geometry, hstore, text) does not exist
LINE 1: SELECT * FROM get_places_for_addr_tags(partition, geometry,
                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT * FROM get_places_for_addr_tags(partition, geometry,
                                                   address, country)
    ORDER BY rank_address, distance, isguess desc
CONTEXT:  PL/pgSQL function insert_addresslines(bigint,smallint,smallint,hstore,geometry,text) line 19 at FOR over SELECT rows
SQL statement "SELECT * FROM insert_addresslines(NEW.place_id, NEW.partition, max_rank,
                                    NEW.address, geom, NEW.country_code)"
PL/pgSQL function placex_update() line 452 at SQL statement


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/nominatim/Nominatim-3.6.0/nominatim/nominatim.py", line 268, in <module>
    Indexer(options).index_boundaries()
  File "/srv/nominatim/Nominatim-3.6.0/nominatim/nominatim.py", line 127, in index_boundaries
    self.index(BoundaryRunner(rank))
  File "/srv/nominatim/Nominatim-3.6.0/nominatim/nominatim.py", line 173, in index
    thread = next(next_thread)
  File "/srv/nominatim/Nominatim-3.6.0/nominatim/nominatim.py", line 194, in find_free_thread
    if thread.is_done():
  File "/srv/nominatim/Nominatim-3.6.0/nominatim/indexer/db.py", line 108, in is_done
    except psycopg2.errors.DeadlockDetected:
AttributeError: module 'psycopg2' has no attribute 'errors'
Error: 1
```

The previous version (3.5.2) was installed in the folder `/srv/nominatim/build`, I installed 3.6.0 to `/srv/nominatim/build-3.6.0` and adapted all paths in config files and webserver, accordingly. Can this be causing all this trouble?

**Comment by mtmail** [comment]
Just double-checking: have you run the steps in the migration guide? http://nominatim.org/release-docs/latest/admin/Migration/#350-360

> AttributeError: module 'psycopg2' has no attribute 'errors'

I think that got fixed with https://github.com/osm-search/Nominatim/pull/2185 in February, but Nominatim 3.6 was released in December so it's not part of 3.6

**Comment by eastclintw00d** [comment]
Yes, I did.

**Comment by eastclintw00d** [comment]
I renamed the old build folder and ran `./utils/setup.php --create--functions`. But unfortunately, it did not fix the problem. I still get the same errors as above.

**Comment by lonvia** [comment]
Sorry, the full function update command should have been: `./utils/setup.php --create-functions --enable-diff-updates --create-partition-functions`. Run this and the issues should be fixed.

**Comment by eastclintw00d** [comment]
Thanks, looks good so far.
